// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ca_contract_impl.proto
// </auto-generated>
// Original file comments:
// *
// CA contract.
#pragma warning disable 0414, 1591
#region Designer generated code

using System.Collections.Generic;
using aelf = global::AElf.CSharp.Core;

namespace Portkey.Contracts.CA {

  #region Events
  public partial class ManagerApproved : aelf::IEvent<ManagerApproved>
  {
    public global::System.Collections.Generic.IEnumerable<ManagerApproved> GetIndexed()
    {
      return new List<ManagerApproved>
      {
      new ManagerApproved
      {
        Platform = Platform
      },
      };
    }

    public ManagerApproved GetNonIndexed()
    {
      return new ManagerApproved
      {
        CaHash = CaHash,
        Spender = Spender,
        Symbol = Symbol,
        Amount = Amount,
      };
    }
  }

  public partial class DefaultTokenTransferLimitChanged : aelf::IEvent<DefaultTokenTransferLimitChanged>
  {
    public global::System.Collections.Generic.IEnumerable<DefaultTokenTransferLimitChanged> GetIndexed()
    {
      return new List<DefaultTokenTransferLimitChanged>
      {
      };
    }

    public DefaultTokenTransferLimitChanged GetNonIndexed()
    {
      return new DefaultTokenTransferLimitChanged
      {
        Symbol = Symbol,
        TransferLimit = TransferLimit,
      };
    }
  }

  public partial class ForbiddenForwardCallContractMethodChanged : aelf::IEvent<ForbiddenForwardCallContractMethodChanged>
  {
    public global::System.Collections.Generic.IEnumerable<ForbiddenForwardCallContractMethodChanged> GetIndexed()
    {
      return new List<ForbiddenForwardCallContractMethodChanged>
      {
      };
    }

    public ForbiddenForwardCallContractMethodChanged GetNonIndexed()
    {
      return new ForbiddenForwardCallContractMethodChanged
      {
        MethodName = MethodName,
        Address = Address,
        Forbidden = Forbidden,
      };
    }
  }

  public partial class TransferLimitChanged : aelf::IEvent<TransferLimitChanged>
  {
    public global::System.Collections.Generic.IEnumerable<TransferLimitChanged> GetIndexed()
    {
      return new List<TransferLimitChanged>
      {
      new TransferLimitChanged
      {
        CaHash = CaHash
      },
      new TransferLimitChanged
      {
        Symbol = Symbol
      },
      new TransferLimitChanged
      {
        SingleLimit = SingleLimit
      },
      new TransferLimitChanged
      {
        DailyLimit = DailyLimit
      },
      new TransferLimitChanged
      {
        Platform = Platform
      },
      };
    }

    public TransferLimitChanged GetNonIndexed()
    {
      return new TransferLimitChanged
      {
      };
    }
  }

  public partial class ManagerTransferred : aelf::IEvent<ManagerTransferred>
  {
    public global::System.Collections.Generic.IEnumerable<ManagerTransferred> GetIndexed()
    {
      return new List<ManagerTransferred>
      {
      new ManagerTransferred
      {
        CaHash = CaHash
      },
      new ManagerTransferred
      {
        To = To
      },
      new ManagerTransferred
      {
        Symbol = Symbol
      },
      new ManagerTransferred
      {
        Platform = Platform
      },
      };
    }

    public ManagerTransferred GetNonIndexed()
    {
      return new ManagerTransferred
      {
        Amount = Amount,
        Memo = Memo,
      };
    }
  }

  public partial class TransferSecurityThresholdChanged : aelf::IEvent<TransferSecurityThresholdChanged>
  {
    public global::System.Collections.Generic.IEnumerable<TransferSecurityThresholdChanged> GetIndexed()
    {
      return new List<TransferSecurityThresholdChanged>
      {
      };
    }

    public TransferSecurityThresholdChanged GetNonIndexed()
    {
      return new TransferSecurityThresholdChanged
      {
        Symbol = Symbol,
        GuardianThreshold = GuardianThreshold,
        BalanceThreshold = BalanceThreshold,
      };
    }
  }

  public partial class ProjectDelegateeRegistered : aelf::IEvent<ProjectDelegateeRegistered>
  {
    public global::System.Collections.Generic.IEnumerable<ProjectDelegateeRegistered> GetIndexed()
    {
      return new List<ProjectDelegateeRegistered>
      {
      new ProjectDelegateeRegistered
      {
        ProjectDelegateHash = ProjectDelegateHash
      },
      new ProjectDelegateeRegistered
      {
        Controller = Controller
      },
      new ProjectDelegateeRegistered
      {
        DelegateeHashList = DelegateeHashList
      },
      new ProjectDelegateeRegistered
      {
        DelegateeAddressList = DelegateeAddressList
      },
      };
    }

    public ProjectDelegateeRegistered GetNonIndexed()
    {
      return new ProjectDelegateeRegistered
      {
      };
    }
  }

  public partial class CAServerAdded : aelf::IEvent<CAServerAdded>
  {
    public global::System.Collections.Generic.IEnumerable<CAServerAdded> GetIndexed()
    {
      return new List<CAServerAdded>
      {
      };
    }

    public CAServerAdded GetNonIndexed()
    {
      return new CAServerAdded
      {
        CaSeverAdded = CaSeverAdded,
      };
    }
  }

  public partial class CAServerRemoved : aelf::IEvent<CAServerRemoved>
  {
    public global::System.Collections.Generic.IEnumerable<CAServerRemoved> GetIndexed()
    {
      return new List<CAServerRemoved>
      {
      };
    }

    public CAServerRemoved GetNonIndexed()
    {
      return new CAServerRemoved
      {
        CaServerRemoved = CaServerRemoved,
      };
    }
  }

  public partial class VerifierServerEndPointsAdded : aelf::IEvent<VerifierServerEndPointsAdded>
  {
    public global::System.Collections.Generic.IEnumerable<VerifierServerEndPointsAdded> GetIndexed()
    {
      return new List<VerifierServerEndPointsAdded>
      {
      new VerifierServerEndPointsAdded
      {
        VerifierServer = VerifierServer
      },
      };
    }

    public VerifierServerEndPointsAdded GetNonIndexed()
    {
      return new VerifierServerEndPointsAdded
      {
      };
    }
  }

  public partial class VerifierServerEndPointsRemoved : aelf::IEvent<VerifierServerEndPointsRemoved>
  {
    public global::System.Collections.Generic.IEnumerable<VerifierServerEndPointsRemoved> GetIndexed()
    {
      return new List<VerifierServerEndPointsRemoved>
      {
      new VerifierServerEndPointsRemoved
      {
        VerifierServer = VerifierServer
      },
      };
    }

    public VerifierServerEndPointsRemoved GetNonIndexed()
    {
      return new VerifierServerEndPointsRemoved
      {
      };
    }
  }

  public partial class VerifierServerRemoved : aelf::IEvent<VerifierServerRemoved>
  {
    public global::System.Collections.Generic.IEnumerable<VerifierServerRemoved> GetIndexed()
    {
      return new List<VerifierServerRemoved>
      {
      new VerifierServerRemoved
      {
        VerifierServer = VerifierServer
      },
      };
    }

    public VerifierServerRemoved GetNonIndexed()
    {
      return new VerifierServerRemoved
      {
      };
    }
  }

  public partial class JwtIssuerCreated : aelf::IEvent<JwtIssuerCreated>
  {
    public global::System.Collections.Generic.IEnumerable<JwtIssuerCreated> GetIndexed()
    {
      return new List<JwtIssuerCreated>
      {
      };
    }

    public JwtIssuerCreated GetNonIndexed()
    {
      return new JwtIssuerCreated
      {
        Issuer = Issuer,
        JwksEndpoint = JwksEndpoint,
      };
    }
  }

  public partial class OracleDataFeedsTaskStarted : aelf::IEvent<OracleDataFeedsTaskStarted>
  {
    public global::System.Collections.Generic.IEnumerable<OracleDataFeedsTaskStarted> GetIndexed()
    {
      return new List<OracleDataFeedsTaskStarted>
      {
      };
    }

    public OracleDataFeedsTaskStarted GetNonIndexed()
    {
      return new OracleDataFeedsTaskStarted
      {
        SubscriptionId = SubscriptionId,
        RequestTypeIndex = RequestTypeIndex,
        SpecificData = SpecificData,
      };
    }
  }

  public partial class CAHolderErrorOccured : aelf::IEvent<CAHolderErrorOccured>
  {
    public global::System.Collections.Generic.IEnumerable<CAHolderErrorOccured> GetIndexed()
    {
      return new List<CAHolderErrorOccured>
      {
      };
    }

    public CAHolderErrorOccured GetNonIndexed()
    {
      return new CAHolderErrorOccured
      {
        ErrorMessage = ErrorMessage,
      };
    }
  }

  #endregion
  public static partial class CAContractImplContainer
  {
    static readonly string __ServiceName = "caimpl.CAContractImpl";

    #region Marshallers
    static readonly aelf::Marshaller<global::AElf.Types.Transaction> __Marshaller_aelf_Transaction = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Types.Transaction.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Standards.ACS2.ResourceInfo> __Marshaller_acs2_ResourceInfo = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Standards.ACS2.ResourceInfo.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.InitializeInput> __Marshaller_ca_InitializeInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.InitializeInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_google_protobuf_Empty = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Empty.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.CreateCAHolderInput> __Marshaller_ca_CreateCAHolderInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.CreateCAHolderInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.ReportPreCrossChainSyncHolderInfoInput> __Marshaller_ca_ReportPreCrossChainSyncHolderInfoInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.ReportPreCrossChainSyncHolderInfoInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.AddGuardianInput> __Marshaller_ca_AddGuardianInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.AddGuardianInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.RemoveGuardianInput> __Marshaller_ca_RemoveGuardianInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.RemoveGuardianInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.UpdateGuardianInput> __Marshaller_ca_UpdateGuardianInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.UpdateGuardianInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.SetGuardianForLoginInput> __Marshaller_ca_SetGuardianForLoginInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.SetGuardianForLoginInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.UnsetGuardianForLoginInput> __Marshaller_ca_UnsetGuardianForLoginInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.UnsetGuardianForLoginInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.ManagerForwardCallInput> __Marshaller_ca_ManagerForwardCallInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.ManagerForwardCallInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.ManagerTransferInput> __Marshaller_ca_ManagerTransferInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.ManagerTransferInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.ManagerTransferFromInput> __Marshaller_ca_ManagerTransferFromInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.ManagerTransferFromInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.SocialRecoveryInput> __Marshaller_ca_SocialRecoveryInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.SocialRecoveryInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.IsManagerReadOnlyInput> __Marshaller_ca_IsManagerReadOnlyInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.IsManagerReadOnlyInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Google.Protobuf.WellKnownTypes.BoolValue> __Marshaller_google_protobuf_BoolValue = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.BoolValue.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.RemoveReadOnlyManagerInput> __Marshaller_ca_RemoveReadOnlyManagerInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.RemoveReadOnlyManagerInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.AddManagerInfoInput> __Marshaller_ca_AddManagerInfoInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.AddManagerInfoInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.RemoveManagerInfoInput> __Marshaller_ca_RemoveManagerInfoInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.RemoveManagerInfoInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.RemoveOtherManagerInfoInput> __Marshaller_ca_RemoveOtherManagerInfoInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.RemoveOtherManagerInfoInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.RemoveOtherManagerInfosInput> __Marshaller_ca_RemoveOtherManagerInfosInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.RemoveOtherManagerInfosInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.UpdateManagerInfosInput> __Marshaller_ca_UpdateManagerInfosInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.UpdateManagerInfosInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.GetHolderInfoInput> __Marshaller_ca_GetHolderInfoInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.GetHolderInfoInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.GetHolderInfoOutput> __Marshaller_ca_GetHolderInfoOutput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.GetHolderInfoOutput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.ValidateCAHolderInfoWithManagerInfosExistsInput> __Marshaller_ca_ValidateCAHolderInfoWithManagerInfosExistsInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.ValidateCAHolderInfoWithManagerInfosExistsInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.ValidateStrategyInput> __Marshaller_ca_ValidateStrategyInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.ValidateStrategyInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.ValidateStrategyOutput> __Marshaller_ca_ValidateStrategyOutput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.ValidateStrategyOutput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.AdminInput> __Marshaller_ca_AdminInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.AdminInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.AdminOutput> __Marshaller_ca_AdminOutput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.AdminOutput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.SetProjectDelegationFeeInput> __Marshaller_ca_SetProjectDelegationFeeInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.SetProjectDelegationFeeInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.ProjectDelegationFee> __Marshaller_ca_ProjectDelegationFee = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.ProjectDelegationFee.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.SetCheckOperationDetailsInSignatureEnabledInput> __Marshaller_ca_SetCheckOperationDetailsInSignatureEnabledInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.SetCheckOperationDetailsInSignatureEnabledInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.GetCheckOperationDetailsInSignatureEnabledOutput> __Marshaller_ca_GetCheckOperationDetailsInSignatureEnabledOutput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.GetCheckOperationDetailsInSignatureEnabledOutput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.JwtIssuerAndEndpointInput> __Marshaller_ca_JwtIssuerAndEndpointInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.JwtIssuerAndEndpointInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.KidPublicKeyInput> __Marshaller_ca_KidPublicKeyInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.KidPublicKeyInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.StartOracleDataFeedsTaskRequest> __Marshaller_ca_StartOracleDataFeedsTaskRequest = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.StartOracleDataFeedsTaskRequest.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.VerifyZkLoginRequest> __Marshaller_ca_VerifyZkLoginRequest = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.VerifyZkLoginRequest.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.VerifySignatureRequest> __Marshaller_ca_VerifySignatureRequest = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.VerifySignatureRequest.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.ManagerMaxCountInput> __Marshaller_caimpl_ManagerMaxCountInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.ManagerMaxCountInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.CanRemoveManagerMaxCountInput> __Marshaller_caimpl_CanRemoveManagerMaxCountInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.CanRemoveManagerMaxCountInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Google.Protobuf.WellKnownTypes.Int32Value> __Marshaller_google_protobuf_Int32Value = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Int32Value.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.ManagerStatisticsInput> __Marshaller_caimpl_ManagerStatisticsInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.ManagerStatisticsInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.ManagerStatisticsInfoList> __Marshaller_caimpl_ManagerStatisticsInfoList = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.ManagerStatisticsInfoList.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.ManagerApproveInput> __Marshaller_caimpl_ManagerApproveInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.ManagerApproveInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.SetForbiddenForwardCallContractMethodInput> __Marshaller_caimpl_SetForbiddenForwardCallContractMethodInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.SetForbiddenForwardCallContractMethodInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.SetTransferLimitInput> __Marshaller_caimpl_SetTransferLimitInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.SetTransferLimitInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.SetTokenInitialTransferLimitInput> __Marshaller_caimpl_SetTokenInitialTransferLimitInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.SetTokenInitialTransferLimitInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.GetTransferLimitInput> __Marshaller_caimpl_GetTransferLimitInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.GetTransferLimitInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.GetTransferLimitOutput> __Marshaller_caimpl_GetTransferLimitOutput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.GetTransferLimitOutput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.SetDefaultTokenTransferLimitInput> __Marshaller_caimpl_SetDefaultTokenTransferLimitInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.SetDefaultTokenTransferLimitInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.GetDefaultTokenTransferLimitInput> __Marshaller_caimpl_GetDefaultTokenTransferLimitInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.GetDefaultTokenTransferLimitInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.GetDefaultTokenTransferLimitOutput> __Marshaller_caimpl_GetDefaultTokenTransferLimitOutput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.GetDefaultTokenTransferLimitOutput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.SetTransferSecurityThresholdInput> __Marshaller_caimpl_SetTransferSecurityThresholdInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.SetTransferSecurityThresholdInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.GetTransferSecurityCheckResultInput> __Marshaller_caimpl_GetTransferSecurityCheckResultInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.GetTransferSecurityCheckResultInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.GetTransferSecurityCheckResultOutput> __Marshaller_caimpl_GetTransferSecurityCheckResultOutput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.GetTransferSecurityCheckResultOutput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.RegisterProjectDelegateeInput> __Marshaller_caimpl_RegisterProjectDelegateeInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.RegisterProjectDelegateeInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Types.Hash> __Marshaller_aelf_Hash = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Types.Hash.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.AddProjectDelegateeListInput> __Marshaller_caimpl_AddProjectDelegateeListInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.AddProjectDelegateeListInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.RemoveProjectDelegateeListInput> __Marshaller_caimpl_RemoveProjectDelegateeListInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.RemoveProjectDelegateeListInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.SetProjectDelegateControllerInput> __Marshaller_caimpl_SetProjectDelegateControllerInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.SetProjectDelegateControllerInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.SetProjectDelegateSignerInput> __Marshaller_caimpl_SetProjectDelegateSignerInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.SetProjectDelegateSignerInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.WithdrawProjectDelegateeTokenInput> __Marshaller_caimpl_WithdrawProjectDelegateeTokenInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.WithdrawProjectDelegateeTokenInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.GetProjectDelegateInfoOutput> __Marshaller_caimpl_GetProjectDelegateInfoOutput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.GetProjectDelegateInfoOutput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.SetManagerForwardCallParallelInfoInput> __Marshaller_caimpl_SetManagerForwardCallParallelInfoInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.SetManagerForwardCallParallelInfoInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.GetManagerForwardCallParallelInfoInput> __Marshaller_caimpl_GetManagerForwardCallParallelInfoInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.GetManagerForwardCallParallelInfoInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.GetManagerForwardCallParallelInfoOutput> __Marshaller_caimpl_GetManagerForwardCallParallelInfoOutput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.GetManagerForwardCallParallelInfoOutput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.AssignProjectDelegateeInput> __Marshaller_caimpl_AssignProjectDelegateeInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.AssignProjectDelegateeInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.RemoveProjectDelegateeInput> __Marshaller_caimpl_RemoveProjectDelegateeInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.RemoveProjectDelegateeInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.WhitelistTransactions> __Marshaller_caimpl_WhitelistTransactions = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.WhitelistTransactions.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.AddManagerApproveSpenderWhitelistInput> __Marshaller_caimpl_AddManagerApproveSpenderWhitelistInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.AddManagerApproveSpenderWhitelistInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.RemoveManagerApproveSpenderWhitelistInput> __Marshaller_caimpl_RemoveManagerApproveSpenderWhitelistInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.RemoveManagerApproveSpenderWhitelistInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Types.Address> __Marshaller_aelf_Address = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Types.Address.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.AddCAServerInput> __Marshaller_caimpl_AddCAServerInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.AddCAServerInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.RemoveCAServerInput> __Marshaller_caimpl_RemoveCAServerInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.RemoveCAServerInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.GetCAServersOutput> __Marshaller_caimpl_GetCAServersOutput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.GetCAServersOutput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.SyncHolderInfoInput> __Marshaller_caimpl_SyncHolderInfoInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.SyncHolderInfoInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.SyncHolderInfosInput> __Marshaller_caimpl_SyncHolderInfosInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.SyncHolderInfosInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.ControllerInput> __Marshaller_caimpl_ControllerInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.ControllerInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.ControllerOutput> __Marshaller_caimpl_ControllerOutput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.ControllerOutput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.AddVerifierServerEndPointsInput> __Marshaller_caimpl_AddVerifierServerEndPointsInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.AddVerifierServerEndPointsInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.RemoveVerifierServerEndPointsInput> __Marshaller_caimpl_RemoveVerifierServerEndPointsInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.RemoveVerifierServerEndPointsInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.RemoveVerifierServerInput> __Marshaller_caimpl_RemoveVerifierServerInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.RemoveVerifierServerInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.GetVerifierServersOutput> __Marshaller_caimpl_GetVerifierServersOutput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.GetVerifierServersOutput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.VerifyingKey> __Marshaller_caimpl_VerifyingKey = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.VerifyingKey.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Google.Protobuf.WellKnownTypes.StringValue> __Marshaller_google_protobuf_StringValue = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.StringValue.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.KidPublicKeyOutput> __Marshaller_caimpl_KidPublicKeyOutput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.KidPublicKeyOutput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.ZkNonceList> __Marshaller_caimpl_ZkNonceList = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.ZkNonceList.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.CurrentKids> __Marshaller_caimpl_CurrentKids = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.CurrentKids.Parser.ParseFrom);
    #endregion

    #region Methods
    static readonly aelf::Method<global::AElf.Types.Transaction, global::AElf.Standards.ACS2.ResourceInfo> __Method_GetResourceInfo = new aelf::Method<global::AElf.Types.Transaction, global::AElf.Standards.ACS2.ResourceInfo>(
        aelf::MethodType.View,
        __ServiceName,
        "GetResourceInfo",
        __Marshaller_aelf_Transaction,
        __Marshaller_acs2_ResourceInfo);

    static readonly aelf::Method<global::Portkey.Contracts.CA.InitializeInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Initialize = new aelf::Method<global::Portkey.Contracts.CA.InitializeInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "Initialize",
        __Marshaller_ca_InitializeInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Portkey.Contracts.CA.CreateCAHolderInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_CreateCAHolder = new aelf::Method<global::Portkey.Contracts.CA.CreateCAHolderInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "CreateCAHolder",
        __Marshaller_ca_CreateCAHolderInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Portkey.Contracts.CA.ReportPreCrossChainSyncHolderInfoInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_ReportPreCrossChainSyncHolderInfo = new aelf::Method<global::Portkey.Contracts.CA.ReportPreCrossChainSyncHolderInfoInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "ReportPreCrossChainSyncHolderInfo",
        __Marshaller_ca_ReportPreCrossChainSyncHolderInfoInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Portkey.Contracts.CA.AddGuardianInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_AddGuardian = new aelf::Method<global::Portkey.Contracts.CA.AddGuardianInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "AddGuardian",
        __Marshaller_ca_AddGuardianInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Portkey.Contracts.CA.RemoveGuardianInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_RemoveGuardian = new aelf::Method<global::Portkey.Contracts.CA.RemoveGuardianInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "RemoveGuardian",
        __Marshaller_ca_RemoveGuardianInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Portkey.Contracts.CA.UpdateGuardianInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_UpdateGuardian = new aelf::Method<global::Portkey.Contracts.CA.UpdateGuardianInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "UpdateGuardian",
        __Marshaller_ca_UpdateGuardianInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Portkey.Contracts.CA.SetGuardianForLoginInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetGuardianForLogin = new aelf::Method<global::Portkey.Contracts.CA.SetGuardianForLoginInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetGuardianForLogin",
        __Marshaller_ca_SetGuardianForLoginInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Portkey.Contracts.CA.UnsetGuardianForLoginInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_UnsetGuardianForLogin = new aelf::Method<global::Portkey.Contracts.CA.UnsetGuardianForLoginInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "UnsetGuardianForLogin",
        __Marshaller_ca_UnsetGuardianForLoginInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Portkey.Contracts.CA.ManagerForwardCallInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_ManagerForwardCall = new aelf::Method<global::Portkey.Contracts.CA.ManagerForwardCallInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "ManagerForwardCall",
        __Marshaller_ca_ManagerForwardCallInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Portkey.Contracts.CA.ManagerTransferInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_ManagerTransfer = new aelf::Method<global::Portkey.Contracts.CA.ManagerTransferInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "ManagerTransfer",
        __Marshaller_ca_ManagerTransferInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Portkey.Contracts.CA.ManagerTransferFromInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_ManagerTransferFrom = new aelf::Method<global::Portkey.Contracts.CA.ManagerTransferFromInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "ManagerTransferFrom",
        __Marshaller_ca_ManagerTransferFromInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Portkey.Contracts.CA.SocialRecoveryInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SocialRecovery = new aelf::Method<global::Portkey.Contracts.CA.SocialRecoveryInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SocialRecovery",
        __Marshaller_ca_SocialRecoveryInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Portkey.Contracts.CA.IsManagerReadOnlyInput, global::Google.Protobuf.WellKnownTypes.BoolValue> __Method_IsManagerReadOnly = new aelf::Method<global::Portkey.Contracts.CA.IsManagerReadOnlyInput, global::Google.Protobuf.WellKnownTypes.BoolValue>(
        aelf::MethodType.View,
        __ServiceName,
        "IsManagerReadOnly",
        __Marshaller_ca_IsManagerReadOnlyInput,
        __Marshaller_google_protobuf_BoolValue);

    static readonly aelf::Method<global::Portkey.Contracts.CA.RemoveReadOnlyManagerInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_RemoveReadOnlyManager = new aelf::Method<global::Portkey.Contracts.CA.RemoveReadOnlyManagerInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "RemoveReadOnlyManager",
        __Marshaller_ca_RemoveReadOnlyManagerInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Portkey.Contracts.CA.AddManagerInfoInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_AddManagerInfo = new aelf::Method<global::Portkey.Contracts.CA.AddManagerInfoInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "AddManagerInfo",
        __Marshaller_ca_AddManagerInfoInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Portkey.Contracts.CA.RemoveManagerInfoInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_RemoveManagerInfo = new aelf::Method<global::Portkey.Contracts.CA.RemoveManagerInfoInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "RemoveManagerInfo",
        __Marshaller_ca_RemoveManagerInfoInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Portkey.Contracts.CA.RemoveOtherManagerInfoInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_RemoveOtherManagerInfo = new aelf::Method<global::Portkey.Contracts.CA.RemoveOtherManagerInfoInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "RemoveOtherManagerInfo",
        __Marshaller_ca_RemoveOtherManagerInfoInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Portkey.Contracts.CA.RemoveOtherManagerInfosInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_RemoveOtherManagerInfos = new aelf::Method<global::Portkey.Contracts.CA.RemoveOtherManagerInfosInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "RemoveOtherManagerInfos",
        __Marshaller_ca_RemoveOtherManagerInfosInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Portkey.Contracts.CA.UpdateManagerInfosInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_UpdateManagerInfos = new aelf::Method<global::Portkey.Contracts.CA.UpdateManagerInfosInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "UpdateManagerInfos",
        __Marshaller_ca_UpdateManagerInfosInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Portkey.Contracts.CA.GetHolderInfoInput, global::Portkey.Contracts.CA.GetHolderInfoOutput> __Method_GetHolderInfo = new aelf::Method<global::Portkey.Contracts.CA.GetHolderInfoInput, global::Portkey.Contracts.CA.GetHolderInfoOutput>(
        aelf::MethodType.View,
        __ServiceName,
        "GetHolderInfo",
        __Marshaller_ca_GetHolderInfoInput,
        __Marshaller_ca_GetHolderInfoOutput);

    static readonly aelf::Method<global::Portkey.Contracts.CA.ValidateCAHolderInfoWithManagerInfosExistsInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_ValidateCAHolderInfoWithManagerInfosExists = new aelf::Method<global::Portkey.Contracts.CA.ValidateCAHolderInfoWithManagerInfosExistsInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "ValidateCAHolderInfoWithManagerInfosExists",
        __Marshaller_ca_ValidateCAHolderInfoWithManagerInfosExistsInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Portkey.Contracts.CA.ValidateStrategyInput, global::Portkey.Contracts.CA.ValidateStrategyOutput> __Method_ValidateStrategy = new aelf::Method<global::Portkey.Contracts.CA.ValidateStrategyInput, global::Portkey.Contracts.CA.ValidateStrategyOutput>(
        aelf::MethodType.View,
        __ServiceName,
        "ValidateStrategy",
        __Marshaller_ca_ValidateStrategyInput,
        __Marshaller_ca_ValidateStrategyOutput);

    static readonly aelf::Method<global::Portkey.Contracts.CA.AdminInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_ChangeAdmin = new aelf::Method<global::Portkey.Contracts.CA.AdminInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "ChangeAdmin",
        __Marshaller_ca_AdminInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Portkey.Contracts.CA.AdminOutput> __Method_GetAdmin = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Portkey.Contracts.CA.AdminOutput>(
        aelf::MethodType.View,
        __ServiceName,
        "GetAdmin",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_ca_AdminOutput);

    static readonly aelf::Method<global::Portkey.Contracts.CA.SetProjectDelegationFeeInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetProjectDelegationFee = new aelf::Method<global::Portkey.Contracts.CA.SetProjectDelegationFeeInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetProjectDelegationFee",
        __Marshaller_ca_SetProjectDelegationFeeInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Portkey.Contracts.CA.ProjectDelegationFee> __Method_GetProjectDelegationFee = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Portkey.Contracts.CA.ProjectDelegationFee>(
        aelf::MethodType.View,
        __ServiceName,
        "GetProjectDelegationFee",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_ca_ProjectDelegationFee);

    static readonly aelf::Method<global::Portkey.Contracts.CA.SetCheckOperationDetailsInSignatureEnabledInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetCheckOperationDetailsInSignatureEnabled = new aelf::Method<global::Portkey.Contracts.CA.SetCheckOperationDetailsInSignatureEnabledInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetCheckOperationDetailsInSignatureEnabled",
        __Marshaller_ca_SetCheckOperationDetailsInSignatureEnabledInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Portkey.Contracts.CA.GetCheckOperationDetailsInSignatureEnabledOutput> __Method_GetCheckOperationDetailsInSignatureEnabled = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Portkey.Contracts.CA.GetCheckOperationDetailsInSignatureEnabledOutput>(
        aelf::MethodType.View,
        __ServiceName,
        "GetCheckOperationDetailsInSignatureEnabled",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_ca_GetCheckOperationDetailsInSignatureEnabledOutput);

    static readonly aelf::Method<global::Portkey.Contracts.CA.JwtIssuerAndEndpointInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_AddOrUpdateJwtIssuer = new aelf::Method<global::Portkey.Contracts.CA.JwtIssuerAndEndpointInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "AddOrUpdateJwtIssuer",
        __Marshaller_ca_JwtIssuerAndEndpointInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Portkey.Contracts.CA.JwtIssuerAndEndpointInput, global::Google.Protobuf.WellKnownTypes.BoolValue> __Method_IsValidIssuer = new aelf::Method<global::Portkey.Contracts.CA.JwtIssuerAndEndpointInput, global::Google.Protobuf.WellKnownTypes.BoolValue>(
        aelf::MethodType.View,
        __ServiceName,
        "IsValidIssuer",
        __Marshaller_ca_JwtIssuerAndEndpointInput,
        __Marshaller_google_protobuf_BoolValue);

    static readonly aelf::Method<global::Portkey.Contracts.CA.KidPublicKeyInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_AddKidPublicKey = new aelf::Method<global::Portkey.Contracts.CA.KidPublicKeyInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "AddKidPublicKey",
        __Marshaller_ca_KidPublicKeyInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Portkey.Contracts.CA.StartOracleDataFeedsTaskRequest, global::Google.Protobuf.WellKnownTypes.Empty> __Method_StartOracleDataFeedsTask = new aelf::Method<global::Portkey.Contracts.CA.StartOracleDataFeedsTaskRequest, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "StartOracleDataFeedsTask",
        __Marshaller_ca_StartOracleDataFeedsTaskRequest,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Portkey.Contracts.CA.VerifyZkLoginRequest, global::Google.Protobuf.WellKnownTypes.BoolValue> __Method_VerifyZkLogin = new aelf::Method<global::Portkey.Contracts.CA.VerifyZkLoginRequest, global::Google.Protobuf.WellKnownTypes.BoolValue>(
        aelf::MethodType.View,
        __ServiceName,
        "VerifyZkLogin",
        __Marshaller_ca_VerifyZkLoginRequest,
        __Marshaller_google_protobuf_BoolValue);

    static readonly aelf::Method<global::Portkey.Contracts.CA.VerifySignatureRequest, global::Google.Protobuf.WellKnownTypes.BoolValue> __Method_VerifySignature = new aelf::Method<global::Portkey.Contracts.CA.VerifySignatureRequest, global::Google.Protobuf.WellKnownTypes.BoolValue>(
        aelf::MethodType.View,
        __ServiceName,
        "VerifySignature",
        __Marshaller_ca_VerifySignatureRequest,
        __Marshaller_google_protobuf_BoolValue);

    static readonly aelf::Method<global::Portkey.Contracts.CA.ManagerMaxCountInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetManagerMaxCount = new aelf::Method<global::Portkey.Contracts.CA.ManagerMaxCountInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetManagerMaxCount",
        __Marshaller_caimpl_ManagerMaxCountInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Portkey.Contracts.CA.CanRemoveManagerMaxCountInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetCanRemoveManagerMaxCount = new aelf::Method<global::Portkey.Contracts.CA.CanRemoveManagerMaxCountInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetCanRemoveManagerMaxCount",
        __Marshaller_caimpl_CanRemoveManagerMaxCountInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int32Value> __Method_GetManagerMaxCount = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int32Value>(
        aelf::MethodType.View,
        __ServiceName,
        "GetManagerMaxCount",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_Int32Value);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int32Value> __Method_GetCanRemoveManagerMaxCount = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int32Value>(
        aelf::MethodType.View,
        __ServiceName,
        "GetCanRemoveManagerMaxCount",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_Int32Value);

    static readonly aelf::Method<global::Portkey.Contracts.CA.ManagerStatisticsInput, global::Portkey.Contracts.CA.ManagerStatisticsInfoList> __Method_GetManagerTransactionStatistics = new aelf::Method<global::Portkey.Contracts.CA.ManagerStatisticsInput, global::Portkey.Contracts.CA.ManagerStatisticsInfoList>(
        aelf::MethodType.View,
        __ServiceName,
        "GetManagerTransactionStatistics",
        __Marshaller_caimpl_ManagerStatisticsInput,
        __Marshaller_caimpl_ManagerStatisticsInfoList);

    static readonly aelf::Method<global::Portkey.Contracts.CA.ManagerApproveInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_ManagerApprove = new aelf::Method<global::Portkey.Contracts.CA.ManagerApproveInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "ManagerApprove",
        __Marshaller_caimpl_ManagerApproveInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Portkey.Contracts.CA.SetForbiddenForwardCallContractMethodInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetForbiddenForwardCallContractMethod = new aelf::Method<global::Portkey.Contracts.CA.SetForbiddenForwardCallContractMethodInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetForbiddenForwardCallContractMethod",
        __Marshaller_caimpl_SetForbiddenForwardCallContractMethodInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Portkey.Contracts.CA.SetTransferLimitInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetTransferLimit = new aelf::Method<global::Portkey.Contracts.CA.SetTransferLimitInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetTransferLimit",
        __Marshaller_caimpl_SetTransferLimitInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Portkey.Contracts.CA.SetTokenInitialTransferLimitInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetTokenInitialTransferLimit = new aelf::Method<global::Portkey.Contracts.CA.SetTokenInitialTransferLimitInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetTokenInitialTransferLimit",
        __Marshaller_caimpl_SetTokenInitialTransferLimitInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Portkey.Contracts.CA.GetTransferLimitInput, global::Portkey.Contracts.CA.GetTransferLimitOutput> __Method_GetTransferLimit = new aelf::Method<global::Portkey.Contracts.CA.GetTransferLimitInput, global::Portkey.Contracts.CA.GetTransferLimitOutput>(
        aelf::MethodType.View,
        __ServiceName,
        "GetTransferLimit",
        __Marshaller_caimpl_GetTransferLimitInput,
        __Marshaller_caimpl_GetTransferLimitOutput);

    static readonly aelf::Method<global::Portkey.Contracts.CA.SetDefaultTokenTransferLimitInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetDefaultTokenTransferLimit = new aelf::Method<global::Portkey.Contracts.CA.SetDefaultTokenTransferLimitInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetDefaultTokenTransferLimit",
        __Marshaller_caimpl_SetDefaultTokenTransferLimitInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Portkey.Contracts.CA.GetDefaultTokenTransferLimitInput, global::Portkey.Contracts.CA.GetDefaultTokenTransferLimitOutput> __Method_GetDefaultTokenTransferLimit = new aelf::Method<global::Portkey.Contracts.CA.GetDefaultTokenTransferLimitInput, global::Portkey.Contracts.CA.GetDefaultTokenTransferLimitOutput>(
        aelf::MethodType.View,
        __ServiceName,
        "GetDefaultTokenTransferLimit",
        __Marshaller_caimpl_GetDefaultTokenTransferLimitInput,
        __Marshaller_caimpl_GetDefaultTokenTransferLimitOutput);

    static readonly aelf::Method<global::Portkey.Contracts.CA.SetTransferSecurityThresholdInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetTransferSecurityThreshold = new aelf::Method<global::Portkey.Contracts.CA.SetTransferSecurityThresholdInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetTransferSecurityThreshold",
        __Marshaller_caimpl_SetTransferSecurityThresholdInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Portkey.Contracts.CA.GetTransferSecurityCheckResultInput, global::Portkey.Contracts.CA.GetTransferSecurityCheckResultOutput> __Method_GetTransferSecurityCheckResult = new aelf::Method<global::Portkey.Contracts.CA.GetTransferSecurityCheckResultInput, global::Portkey.Contracts.CA.GetTransferSecurityCheckResultOutput>(
        aelf::MethodType.View,
        __ServiceName,
        "GetTransferSecurityCheckResult",
        __Marshaller_caimpl_GetTransferSecurityCheckResultInput,
        __Marshaller_caimpl_GetTransferSecurityCheckResultOutput);

    static readonly aelf::Method<global::Portkey.Contracts.CA.RegisterProjectDelegateeInput, global::AElf.Types.Hash> __Method_RegisterProjectDelegatee = new aelf::Method<global::Portkey.Contracts.CA.RegisterProjectDelegateeInput, global::AElf.Types.Hash>(
        aelf::MethodType.Action,
        __ServiceName,
        "RegisterProjectDelegatee",
        __Marshaller_caimpl_RegisterProjectDelegateeInput,
        __Marshaller_aelf_Hash);

    static readonly aelf::Method<global::Portkey.Contracts.CA.AddProjectDelegateeListInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_AddProjectDelegateeList = new aelf::Method<global::Portkey.Contracts.CA.AddProjectDelegateeListInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "AddProjectDelegateeList",
        __Marshaller_caimpl_AddProjectDelegateeListInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Portkey.Contracts.CA.RemoveProjectDelegateeListInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_RemoveProjectDelegateeList = new aelf::Method<global::Portkey.Contracts.CA.RemoveProjectDelegateeListInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "RemoveProjectDelegateeList",
        __Marshaller_caimpl_RemoveProjectDelegateeListInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Portkey.Contracts.CA.SetProjectDelegateControllerInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetProjectDelegateController = new aelf::Method<global::Portkey.Contracts.CA.SetProjectDelegateControllerInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetProjectDelegateController",
        __Marshaller_caimpl_SetProjectDelegateControllerInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Portkey.Contracts.CA.SetProjectDelegateSignerInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetProjectDelegateSigner = new aelf::Method<global::Portkey.Contracts.CA.SetProjectDelegateSignerInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetProjectDelegateSigner",
        __Marshaller_caimpl_SetProjectDelegateSignerInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Portkey.Contracts.CA.WithdrawProjectDelegateeTokenInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_WithdrawProjectDelegateeToken = new aelf::Method<global::Portkey.Contracts.CA.WithdrawProjectDelegateeTokenInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "WithdrawProjectDelegateeToken",
        __Marshaller_caimpl_WithdrawProjectDelegateeTokenInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Types.Hash, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetCaProjectDelegateHash = new aelf::Method<global::AElf.Types.Hash, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetCaProjectDelegateHash",
        __Marshaller_aelf_Hash,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Types.Hash> __Method_GetCaProjectDelegateHash = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Types.Hash>(
        aelf::MethodType.Action,
        __ServiceName,
        "GetCaProjectDelegateHash",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_aelf_Hash);

    static readonly aelf::Method<global::AElf.Types.Hash, global::Portkey.Contracts.CA.GetProjectDelegateInfoOutput> __Method_GetProjectDelegatee = new aelf::Method<global::AElf.Types.Hash, global::Portkey.Contracts.CA.GetProjectDelegateInfoOutput>(
        aelf::MethodType.View,
        __ServiceName,
        "GetProjectDelegatee",
        __Marshaller_aelf_Hash,
        __Marshaller_caimpl_GetProjectDelegateInfoOutput);

    static readonly aelf::Method<global::Portkey.Contracts.CA.SetManagerForwardCallParallelInfoInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetManagerForwardCallParallelInfo = new aelf::Method<global::Portkey.Contracts.CA.SetManagerForwardCallParallelInfoInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetManagerForwardCallParallelInfo",
        __Marshaller_caimpl_SetManagerForwardCallParallelInfoInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Portkey.Contracts.CA.GetManagerForwardCallParallelInfoInput, global::Portkey.Contracts.CA.GetManagerForwardCallParallelInfoOutput> __Method_GetManagerForwardCallParallelInfo = new aelf::Method<global::Portkey.Contracts.CA.GetManagerForwardCallParallelInfoInput, global::Portkey.Contracts.CA.GetManagerForwardCallParallelInfoOutput>(
        aelf::MethodType.View,
        __ServiceName,
        "GetManagerForwardCallParallelInfo",
        __Marshaller_caimpl_GetManagerForwardCallParallelInfoInput,
        __Marshaller_caimpl_GetManagerForwardCallParallelInfoOutput);

    static readonly aelf::Method<global::Portkey.Contracts.CA.AssignProjectDelegateeInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_AssignProjectDelegatee = new aelf::Method<global::Portkey.Contracts.CA.AssignProjectDelegateeInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "AssignProjectDelegatee",
        __Marshaller_caimpl_AssignProjectDelegateeInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Portkey.Contracts.CA.RemoveProjectDelegateeInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_RemoveProjectDelegatee = new aelf::Method<global::Portkey.Contracts.CA.RemoveProjectDelegateeInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "RemoveProjectDelegatee",
        __Marshaller_caimpl_RemoveProjectDelegateeInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Portkey.Contracts.CA.WhitelistTransactions, global::Google.Protobuf.WellKnownTypes.Empty> __Method_AddTransactionWhitelist = new aelf::Method<global::Portkey.Contracts.CA.WhitelistTransactions, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "AddTransactionWhitelist",
        __Marshaller_caimpl_WhitelistTransactions,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Portkey.Contracts.CA.WhitelistTransactions, global::Google.Protobuf.WellKnownTypes.Empty> __Method_RemoveTransactionWhitelist = new aelf::Method<global::Portkey.Contracts.CA.WhitelistTransactions, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "RemoveTransactionWhitelist",
        __Marshaller_caimpl_WhitelistTransactions,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Portkey.Contracts.CA.WhitelistTransactions> __Method_GetTransactionWhitelist = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Portkey.Contracts.CA.WhitelistTransactions>(
        aelf::MethodType.View,
        __ServiceName,
        "GetTransactionWhitelist",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_caimpl_WhitelistTransactions);

    static readonly aelf::Method<global::Portkey.Contracts.CA.AddManagerApproveSpenderWhitelistInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_AddManagerApproveSpenderWhitelist = new aelf::Method<global::Portkey.Contracts.CA.AddManagerApproveSpenderWhitelistInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "AddManagerApproveSpenderWhitelist",
        __Marshaller_caimpl_AddManagerApproveSpenderWhitelistInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Portkey.Contracts.CA.RemoveManagerApproveSpenderWhitelistInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_RemoveManagerApproveSpenderWhitelist = new aelf::Method<global::Portkey.Contracts.CA.RemoveManagerApproveSpenderWhitelistInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "RemoveManagerApproveSpenderWhitelist",
        __Marshaller_caimpl_RemoveManagerApproveSpenderWhitelistInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.BoolValue> __Method_CheckInManagerApproveSpenderWhitelist = new aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.BoolValue>(
        aelf::MethodType.View,
        __ServiceName,
        "CheckInManagerApproveSpenderWhitelist",
        __Marshaller_aelf_Address,
        __Marshaller_google_protobuf_BoolValue);

    static readonly aelf::Method<global::Portkey.Contracts.CA.AddCAServerInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_AddCAServer = new aelf::Method<global::Portkey.Contracts.CA.AddCAServerInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "AddCAServer",
        __Marshaller_caimpl_AddCAServerInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Portkey.Contracts.CA.RemoveCAServerInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_RemoveCAServer = new aelf::Method<global::Portkey.Contracts.CA.RemoveCAServerInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "RemoveCAServer",
        __Marshaller_caimpl_RemoveCAServerInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Portkey.Contracts.CA.GetCAServersOutput> __Method_GetCAServers = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Portkey.Contracts.CA.GetCAServersOutput>(
        aelf::MethodType.View,
        __ServiceName,
        "GetCAServers",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_caimpl_GetCAServersOutput);

    static readonly aelf::Method<global::Portkey.Contracts.CA.SyncHolderInfoInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SyncHolderInfo = new aelf::Method<global::Portkey.Contracts.CA.SyncHolderInfoInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SyncHolderInfo",
        __Marshaller_caimpl_SyncHolderInfoInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Portkey.Contracts.CA.SyncHolderInfosInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SyncHolderInfos = new aelf::Method<global::Portkey.Contracts.CA.SyncHolderInfosInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SyncHolderInfos",
        __Marshaller_caimpl_SyncHolderInfosInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Portkey.Contracts.CA.ControllerInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_AddCreatorController = new aelf::Method<global::Portkey.Contracts.CA.ControllerInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "AddCreatorController",
        __Marshaller_caimpl_ControllerInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Portkey.Contracts.CA.ControllerInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_RemoveCreatorController = new aelf::Method<global::Portkey.Contracts.CA.ControllerInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "RemoveCreatorController",
        __Marshaller_caimpl_ControllerInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Portkey.Contracts.CA.ControllerOutput> __Method_GetCreatorControllers = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Portkey.Contracts.CA.ControllerOutput>(
        aelf::MethodType.View,
        __ServiceName,
        "GetCreatorControllers",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_caimpl_ControllerOutput);

    static readonly aelf::Method<global::Portkey.Contracts.CA.ControllerInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_AddServerController = new aelf::Method<global::Portkey.Contracts.CA.ControllerInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "AddServerController",
        __Marshaller_caimpl_ControllerInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Portkey.Contracts.CA.ControllerInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_RemoveServerController = new aelf::Method<global::Portkey.Contracts.CA.ControllerInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "RemoveServerController",
        __Marshaller_caimpl_ControllerInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Portkey.Contracts.CA.ControllerOutput> __Method_GetServerControllers = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Portkey.Contracts.CA.ControllerOutput>(
        aelf::MethodType.View,
        __ServiceName,
        "GetServerControllers",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_caimpl_ControllerOutput);

    static readonly aelf::Method<global::Portkey.Contracts.CA.AddVerifierServerEndPointsInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_AddVerifierServerEndPoints = new aelf::Method<global::Portkey.Contracts.CA.AddVerifierServerEndPointsInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "AddVerifierServerEndPoints",
        __Marshaller_caimpl_AddVerifierServerEndPointsInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Portkey.Contracts.CA.RemoveVerifierServerEndPointsInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_RemoveVerifierServerEndPoints = new aelf::Method<global::Portkey.Contracts.CA.RemoveVerifierServerEndPointsInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "RemoveVerifierServerEndPoints",
        __Marshaller_caimpl_RemoveVerifierServerEndPointsInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Portkey.Contracts.CA.RemoveVerifierServerInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_RemoveVerifierServer = new aelf::Method<global::Portkey.Contracts.CA.RemoveVerifierServerInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "RemoveVerifierServer",
        __Marshaller_caimpl_RemoveVerifierServerInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Portkey.Contracts.CA.GetVerifierServersOutput> __Method_GetVerifierServers = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Portkey.Contracts.CA.GetVerifierServersOutput>(
        aelf::MethodType.View,
        __ServiceName,
        "GetVerifierServers",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_caimpl_GetVerifierServersOutput);

    static readonly aelf::Method<global::Portkey.Contracts.CA.VerifyingKey, global::Google.Protobuf.WellKnownTypes.Empty> __Method_AddOrUpdateVerifyingKey = new aelf::Method<global::Portkey.Contracts.CA.VerifyingKey, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "AddOrUpdateVerifyingKey",
        __Marshaller_caimpl_VerifyingKey,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::Portkey.Contracts.CA.VerifyingKey> __Method_GetVerifyingKey = new aelf::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::Portkey.Contracts.CA.VerifyingKey>(
        aelf::MethodType.View,
        __ServiceName,
        "GetVerifyingKey",
        __Marshaller_google_protobuf_StringValue,
        __Marshaller_caimpl_VerifyingKey);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::Portkey.Contracts.CA.KidPublicKeyOutput> __Method_GetGooglePublicKeyByKid = new aelf::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::Portkey.Contracts.CA.KidPublicKeyOutput>(
        aelf::MethodType.View,
        __ServiceName,
        "GetGooglePublicKeyByKid",
        __Marshaller_google_protobuf_StringValue,
        __Marshaller_caimpl_KidPublicKeyOutput);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::Portkey.Contracts.CA.KidPublicKeyOutput> __Method_GetApplePublicKeyByKid = new aelf::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::Portkey.Contracts.CA.KidPublicKeyOutput>(
        aelf::MethodType.View,
        __ServiceName,
        "GetApplePublicKeyByKid",
        __Marshaller_google_protobuf_StringValue,
        __Marshaller_caimpl_KidPublicKeyOutput);

    static readonly aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetOracleAddress = new aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetOracleAddress",
        __Marshaller_aelf_Address,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Types.Hash, global::Portkey.Contracts.CA.ZkNonceList> __Method_GetZkNonceListByCaHash = new aelf::Method<global::AElf.Types.Hash, global::Portkey.Contracts.CA.ZkNonceList>(
        aelf::MethodType.View,
        __ServiceName,
        "GetZkNonceListByCaHash",
        __Marshaller_aelf_Hash,
        __Marshaller_caimpl_ZkNonceList);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Portkey.Contracts.CA.CurrentKids> __Method_GetGoogleKids = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Portkey.Contracts.CA.CurrentKids>(
        aelf::MethodType.View,
        __ServiceName,
        "GetGoogleKids",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_caimpl_CurrentKids);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Portkey.Contracts.CA.CurrentKids> __Method_GetAppleKids = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Portkey.Contracts.CA.CurrentKids>(
        aelf::MethodType.View,
        __ServiceName,
        "GetAppleKids",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_caimpl_CurrentKids);

    #endregion

    #region Descriptors
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Portkey.Contracts.CA.CaContractImplReflection.Descriptor.Services[0]; }
    }

    public static global::System.Collections.Generic.IReadOnlyList<global::Google.Protobuf.Reflection.ServiceDescriptor> Descriptors
    {
      get
      {
        return new global::System.Collections.Generic.List<global::Google.Protobuf.Reflection.ServiceDescriptor>()
        {
          global::AElf.Standards.ACS12.Acs12Reflection.Descriptor.Services[0],
          global::AElf.Standards.ACS2.Acs2Reflection.Descriptor.Services[0],
          global::Portkey.Contracts.CA.CaContractReflection.Descriptor.Services[0],
          global::Portkey.Contracts.CA.CaContractImplReflection.Descriptor.Services[0],
        };
      }
    }
    #endregion
  }
}
#endregion

